[lib]
name = "note_tree"
crate-type = ["cdylib"]

[package]
name = "note_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.8.10", features = ["lua51", "vendored", "module"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
